### ISSUE TITLE
What is the diference between the workbench and the linter-verification packages?

### ISSUE THREAD

**Issue by andreffrosa** [Alchiadus/dafny-workbench#3]

**Comment by Alchiadus** [comment]
The `linter-verification` package was my first implementation and only provides a [linter](https://github.com/steelbrain/linter) for Dafny. It consumes version `1.0` of the linter. Back then I was also trying out the Owicki-Gries method of program verification by annotating Dafny files with specific comments that a transpiler could use to produce the (verbose) Dafny program verification conditions necessary to proof the Owicki-Gries program. The `linter-verification` package also had support for that.

During my master thesis I worked on implementing Owicki-Gries directly in Dafny and when version `2.0` of the linter API out came out I had some other ideas to improve working with Dafny in Atom, for example a status bar icon to indicate verification status and a tooltip with some more information. This has no place in a linter package, so I decided to create `dafny-workbench` to support the new API, as well as add some other features I thought useful while working on program verification.

Since graduating I have no longer used Dafny and I recently switched to Visual Studio Code. My Atom packages are not maintained anymore, so I am not sure if they still work.
